### ISSUE TITLE
realm update to 3.0.2 will you support realm 3.x.x ?

### ISSUE THREAD

**Issue by icefox57** [tsrnd/realm-mapper-ios#14]
Got error when update realm

[!] Unable to satisfy the following requirements:

- `RealmSwift (~> 3.0.2)` required by `Podfile`
- `RealmSwift (~> 2.2)` required by `RealmMapper (2.3.1)`

realm update to 3.0.2 will you support realm 3.x.x ?

**Comment by at-daonguyen** [comment]
@icefox57 Sorry for my late reply.
I'll update soon.
